services:
  - type: web
    name: tangyunxuan-backend
    env: python
    buildCommand: "pip install -r src/backend/requirements.txt"
    startCommand: "uvicorn src.backend.main:app --host 0.0.0.0 --port 10000"
    plan: free
    envVars:
      - key: DATABASE_URL
        value: sqlite:///app.db
    rootDir: src/backend